/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ConfidentialComplianceVaultInterface extends Interface {
    getFunction(nameOrSignature: "complianceOfficer" | "confidentialProtocolId" | "deposit" | "getEncryptedBalanceHandle" | "getInvestorMetadata" | "maxRiskClass" | "minKycTier" | "owner" | "registerInvestor" | "renounceOwnership" | "requestWithdrawal" | "setComplianceOfficer" | "transferOwnership" | "updatePolicy"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CompliancePolicyUpdated" | "ConfidentialDeposit" | "ConfidentialWithdrawalRequested" | "InvestorRegistered" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'complianceOfficer', values?: undefined): string;
encodeFunctionData(functionFragment: 'confidentialProtocolId', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getEncryptedBalanceHandle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getInvestorMetadata', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxRiskClass', values?: undefined): string;
encodeFunctionData(functionFragment: 'minKycTier', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerInvestor', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestWithdrawal', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'setComplianceOfficer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePolicy', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'complianceOfficer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confidentialProtocolId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEncryptedBalanceHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestorMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxRiskClass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minKycTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerInvestor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setComplianceOfficer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePolicy', data: BytesLike): Result;
  }

  
    export namespace CompliancePolicyUpdatedEvent {
      export type InputTuple = [minKycTier: BigNumberish, maxRiskClass: BigNumberish];
      export type OutputTuple = [minKycTier: bigint, maxRiskClass: bigint];
      export interface OutputObject {minKycTier: bigint, maxRiskClass: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConfidentialDepositEvent {
      export type InputTuple = [investor: AddressLike];
      export type OutputTuple = [investor: string];
      export interface OutputObject {investor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConfidentialWithdrawalRequestedEvent {
      export type InputTuple = [investor: AddressLike];
      export type OutputTuple = [investor: string];
      export interface OutputObject {investor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvestorRegisteredEvent {
      export type InputTuple = [investor: AddressLike, kycTier: BigNumberish, riskClass: BigNumberish];
      export type OutputTuple = [investor: string, kycTier: bigint, riskClass: bigint];
      export interface OutputObject {investor: string, kycTier: bigint, riskClass: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ConfidentialComplianceVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ConfidentialComplianceVault;
    waitForDeployment(): Promise<this>;

    interface: ConfidentialComplianceVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    complianceOfficer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    confidentialProtocolId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getEncryptedBalanceHandle: TypedContractMethod<
      [investor: AddressLike, ],
      [string],
      'view'
    >
    

    
    getInvestorMetadata: TypedContractMethod<
      [investor: AddressLike, ],
      [[boolean, bigint, bigint] & {isRegistered: boolean, kycTier: bigint, riskClass: bigint }],
      'view'
    >
    

    
    maxRiskClass: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minKycTier: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerInvestor: TypedContractMethod<
      [investor: AddressLike, kycTier: BigNumberish, riskClass: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestWithdrawal: TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setComplianceOfficer: TypedContractMethod<
      [newOfficer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePolicy: TypedContractMethod<
      [newMinKycTier: BigNumberish, newMaxRiskClass: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'complianceOfficer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'confidentialProtocolId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEncryptedBalanceHandle'): TypedContractMethod<
      [investor: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestorMetadata'): TypedContractMethod<
      [investor: AddressLike, ],
      [[boolean, bigint, bigint] & {isRegistered: boolean, kycTier: bigint, riskClass: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'maxRiskClass'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minKycTier'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerInvestor'): TypedContractMethod<
      [investor: AddressLike, kycTier: BigNumberish, riskClass: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestWithdrawal'): TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setComplianceOfficer'): TypedContractMethod<
      [newOfficer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePolicy'): TypedContractMethod<
      [newMinKycTier: BigNumberish, newMaxRiskClass: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CompliancePolicyUpdated'): TypedContractEvent<CompliancePolicyUpdatedEvent.InputTuple, CompliancePolicyUpdatedEvent.OutputTuple, CompliancePolicyUpdatedEvent.OutputObject>;
getEvent(key: 'ConfidentialDeposit'): TypedContractEvent<ConfidentialDepositEvent.InputTuple, ConfidentialDepositEvent.OutputTuple, ConfidentialDepositEvent.OutputObject>;
getEvent(key: 'ConfidentialWithdrawalRequested'): TypedContractEvent<ConfidentialWithdrawalRequestedEvent.InputTuple, ConfidentialWithdrawalRequestedEvent.OutputTuple, ConfidentialWithdrawalRequestedEvent.OutputObject>;
getEvent(key: 'InvestorRegistered'): TypedContractEvent<InvestorRegisteredEvent.InputTuple, InvestorRegisteredEvent.OutputTuple, InvestorRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'CompliancePolicyUpdated(uint8,uint8)': TypedContractEvent<CompliancePolicyUpdatedEvent.InputTuple, CompliancePolicyUpdatedEvent.OutputTuple, CompliancePolicyUpdatedEvent.OutputObject>;
      CompliancePolicyUpdated: TypedContractEvent<CompliancePolicyUpdatedEvent.InputTuple, CompliancePolicyUpdatedEvent.OutputTuple, CompliancePolicyUpdatedEvent.OutputObject>;
    

      'ConfidentialDeposit(address)': TypedContractEvent<ConfidentialDepositEvent.InputTuple, ConfidentialDepositEvent.OutputTuple, ConfidentialDepositEvent.OutputObject>;
      ConfidentialDeposit: TypedContractEvent<ConfidentialDepositEvent.InputTuple, ConfidentialDepositEvent.OutputTuple, ConfidentialDepositEvent.OutputObject>;
    

      'ConfidentialWithdrawalRequested(address)': TypedContractEvent<ConfidentialWithdrawalRequestedEvent.InputTuple, ConfidentialWithdrawalRequestedEvent.OutputTuple, ConfidentialWithdrawalRequestedEvent.OutputObject>;
      ConfidentialWithdrawalRequested: TypedContractEvent<ConfidentialWithdrawalRequestedEvent.InputTuple, ConfidentialWithdrawalRequestedEvent.OutputTuple, ConfidentialWithdrawalRequestedEvent.OutputObject>;
    

      'InvestorRegistered(address,uint8,uint8)': TypedContractEvent<InvestorRegisteredEvent.InputTuple, InvestorRegisteredEvent.OutputTuple, InvestorRegisteredEvent.OutputObject>;
      InvestorRegistered: TypedContractEvent<InvestorRegisteredEvent.InputTuple, InvestorRegisteredEvent.OutputTuple, InvestorRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }