/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConfidentialComplianceVault } from './ConfidentialComplianceVault.js';
export * as factories from './factories/index.js';
export { ConfidentialComplianceVault__factory } from './factories/ConfidentialComplianceVault__factory.js';